import re
from langchain_ollama import ChatOllama
from schema_indexer import retrieve_relevant_schema
from tools import validate_readonly_ast, run_query

# 1. Initialize local lightweight LLM
llm = ChatOllama(model="llama3.2", temperature=0)

# Base Prompt Template
SQL_PROMPT_TEMPLATE = """You are a SQL Data Analyst. Write a single SQLite SELECT query to answer the user's question.

Relevant Database Schema:
{schema}

User Question: {question}
{error_context}

MANDATORY RULES:
1. Return ONLY the raw SQL query inside a ```sql ... ``` block.
2. Use ONLY the table and column names specified in the schema above.
3. The query MUST be a read-only SELECT statement.
"""

def extract_sql_from_text(raw_text: str) -> str:
    """Helper function to cleanly pull SQL from markdown code blocks or plain text."""
    sql_match = re.search(r"```sql\s*(.*?)\s*```", raw_text, re.DOTALL | re.IGNORECASE)
    if sql_match:
        return sql_match.group(1).strip()
    return raw_text.strip()


def run_agent(user_query: str, max_retries: int = 2) -> dict:
    """
    Production-grade Self-Correcting Pipeline:
    1. Semantically retrieves relevant schemas via ChromaDB.
    2. Generates SQL query.
    3. Runs AST Validation & SQLite Execution.
    4. If an error occurs, feeds the exact error back to the LLM to self-heal.
    """
    # Step 1: Vector Schema Retrieval
    retrieved_schema = retrieve_relevant_schema(user_query, top_k=2)
    
    error_context = ""
    last_generated_sql = ""
    
    for attempt in range(1, max_retries + 1):
        # Step 2: Format prompt (including error feedback if on retry)
        prompt = SQL_PROMPT_TEMPLATE.format(
            schema=retrieved_schema,
            question=user_query,
            error_context=error_context
        )
        
        response = llm.invoke(prompt)
        last_generated_sql = extract_sql_from_text(response.content)

        # Step 3: AST Safety Check
        is_safe, security_msg = validate_readonly_ast(last_generated_sql)
        if not is_safe:
            error_context = f"\nCRITICAL: Your previous query '{last_generated_sql}' failed security validation: {security_msg}. Fix it to be a valid read-only SELECT."
            continue

        # Step 4: Database Execution & Auto-Healing
        try:
            db_result = run_query(last_generated_sql)
            return {
                "status": "success",
                "attempts": attempt,
                "schema": retrieved_schema,
                "sql": last_generated_sql,
                "result": db_result
            }
        except Exception as db_err:
            # Capture database error and feed it back for the next retry
            error_context = f"\nCRITICAL: Your previous SQL query '{last_generated_sql}' caused a database error: {str(db_err)}. Check the schema and fix the query."

    return {
        "status": "failed",
        "attempts": max_retries,
        "schema": retrieved_schema,
        "sql": last_generated_sql,
        "result": error_context
    }


if __name__ == "__main__":
    print("=== Testing Self-Correcting SQL Pipeline ===")
    test_query = "What is the total sales amount generated by employee 1?"
    
    res = run_agent(test_query)
    print(f"\nStatus: {res['status'].upper()} (Completed in {res['attempts']} attempt(s))")
    print(f"Generated SQL:\n{res['sql']}")
    print(f"Database Result:\n{res['result']}")