import sqlite3
from agent import run_agent, llm, SQL_PROMPT_TEMPLATE
from schema_indexer import retrieve_relevant_schema
from tools import validate_readonly_ast, run_query
import re

# Benchmark Test Suite (Natural Language -> Gold Standard SQL)
BENCHMARK_SUITE = [
    {
        "id": 1,
        "question": "What is the total sum of all sales?",
        "gold_sql": "SELECT SUM(amount) FROM sales;"
    },
    {
        "id": 2,
        "question": "Which employee has the highest salary?",
        "gold_sql": "SELECT name FROM employees ORDER BY salary DESC LIMIT 1;"
    },
    {
        "id": 3,
        "question": "Find the average salary of employees in Engineering.",
        "gold_sql": "SELECT AVG(salary) FROM employees WHERE department = 'Engineering';"
    },
    {
        "id": 4,
        "question": "What is the total sales amount generated by employee 1?",
        "gold_sql": "SELECT SUM(amount) FROM sales WHERE employee_id = 1;"
    },
    {
        "id": 5,
        "question": "Count the total number of employees in the company.",
        "gold_sql": "SELECT COUNT(*) FROM employees;"
    }
]

def run_evaluation():
    print("=== Running Automated Text-to-SQL Benchmark Suite ===\n")
    
    total_queries = len(BENCHMARK_SUITE)
    ast_valid_count = 0
    execution_correct_count = 0

    for item in BENCHMARK_SUITE:
        qid = item["id"]
        question = item["question"]
        gold_sql = item["gold_sql"]

        print(f"[{qid}/{total_queries}] Testing: '{question}'")

        # 1. RAG Schema Retrieval
        schema = retrieve_relevant_schema(question, top_k=2)

        # 2. SQL Generation
        prompt = SQL_PROMPT_TEMPLATE.format(schema=schema, question=question)
        response = llm.invoke(prompt)
        raw_content = response.content

        # 3. Extract SQL
        sql_match = re.search(r"```sql\s*(.*?)\s*```", raw_content, re.DOTALL | re.IGNORECASE)
        generated_sql = sql_match.group(1).strip() if sql_match else raw_content.strip()

        # 4. Metric 1: AST Safety Validation
        is_safe, msg = validate_readonly_ast(generated_sql)
        if is_safe:
            ast_valid_count += 1

        # 5. Metric 2: Execution Accuracy (EX)
        # Compare actual query results vs Gold Standard query results
        try:
            actual_res = run_query(generated_sql)
            gold_res = run_query(gold_sql)

            if actual_res == gold_res:
                execution_correct_count += 1
                status = "PASS (Exact Match)"
            else:
                status = f"FAIL (Result Mismatch: {actual_res} vs {gold_res})"
        except Exception as e:
            status = f"ERROR ({str(e)})"

        print(f"   Generated: {generated_sql}")
        print(f"   AST Safe:  {is_safe} ({msg})")
        print(f"   Execution: {status}\n")

    ast_pass_rate = (ast_valid_count / total_queries) * 100
    ex_accuracy = (execution_correct_count / total_queries) * 100

    print("==================================================")
    print("                BENCHMARK RESULTS                 ")
    print("==================================================")
    print(f"Total Test Cases:           {total_queries}")
    print(f"AST Safety Pass Rate:       {ast_pass_rate:.1f}%")
    print(f"Execution Accuracy (EX):    {ex_accuracy:.1f}%")
    print("==================================================")


if __name__ == "__main__":
    run_evaluation()